Actually commit to the build repo

diff --git a/.github/workflows/deploy_branches.yml b/.github/workflows/deploy_branches.yml
--- a/.github/workflows/deploy_branches.yml
+++ b/.github/workflows/deploy_branches.yml
@@ -60,27 +60,27 @@ jobs:
       - name: See the status of the git repo
         run: git status
         working-directory: ./server
-      # - name : Commit to the website aka deploy
-      #   run: |
-      #     git config user.name github-deploy-action
-      #     git config user.email hazel-deploy@hazel.org
-      #     git add -A
-      #     git pull --no-edit
-      #     git status
-      #     git diff-index --quiet HEAD || (git commit -m "github-deploy-action-${BRANCH_NAME}"; git push)
-      #   working-directory: ./server
-      # - name: Run Tests
-      #   id: test
-      #   run: |
-      #     eval $(opam env)
-      #     make test
-      #   working-directory: ./source
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   with:
-      #     name: Test Report
-      #     path: junit_tests*.xml
-      #     reporter: java-junit
-      #     fail-on-error: true
-      #     fail-on-empty: true # Use an empty test report to detect when something failed with the test runner
-      #     working-directory: ./source
+      - name : Commit to the website aka deploy
+        run: |
+          git config user.name github-deploy-action
+          git config user.email hazel-deploy@hazel.org
+          git add -A
+          git pull --no-edit
+          git status
+          git diff-index --quiet HEAD || (git commit -m "github-deploy-action-${BRANCH_NAME}"; git push)
+        working-directory: ./server
+      - name: Run Tests
+        id: test
+        run: |
+          eval $(opam env)
+          make test
+        working-directory: ./source
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        with:
+          name: Test Report
+          path: junit_tests*.xml
+          reporter: java-junit
+          fail-on-error: true
+          fail-on-empty: true # Use an empty test report to detect when something failed with the test runner
+          working-directory: ./source
